tokens_dir: gse131907/processed/tokens
model_path: outputs/lung
model_vocab: Geneformer/geneformer/token_dictionary_gc104M.pkl
model_gene_name_dict: Geneformer/geneformer/gene_name_id_dict_gc104M.pkl
max_length: 2048
label_column: BinaryClass
eval_splits:
  - val
  - test
eval_batch_size: 8
output_json: results/lung/lung_eval_metrics.json
